spring:
  application:
    name: FinanceBot
  datasource:
    url: jdbc:postgresql://localhost:5432/financebot
    username: ishenaly
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
bot:
  token: ${BOT_TOKEN}
  username: finance_abit8_bot