create table users
(
    id             bigint generated by default as identity
        primary key,
    chat_id        bigint not null
        constraint uknr2rmfhq6wfp39vcduy7iketb
            unique,
    created_at     timestamp(6),
    currency       varchar(3),
    export_format  varchar(5),
    is_premium     boolean,
    language       varchar(2),
    stats_time     time(6),
    trial_end_date date,
    user_state     varchar(255)
);

alter table users
    owner to ishenaly;

create table categories
(
    id      bigint generated by default as identity
        primary key,
    name    varchar(50),
    type    varchar(10),
    user_id bigint not null
        constraint fkghuylkwuedgl2qahxjt8g41kb
            references users,
    constraint uk3xjtm42xe7moyf7ijqkagoq45
        unique (user_id, name, type)
);

alter table categories
    owner to ishenaly;

create table subscriptions
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    end_date   date,
    start_date date,
    user_id    bigint
        constraint fkhro52ohfqfbay9774bev0qinr
            references users
);

alter table subscriptions
    owner to ishenaly;

create table transactions
(
    id          bigint generated by default as identity
        primary key,
    amount      numeric(38, 2),
    comment     varchar(255),
    created_at  timestamp(6),
    date        date,
    deleted     boolean,
    time        time(6),
    type        varchar(10),
    category_id bigint
        constraint fksqqi7sneo04kast0o138h19mv
            references categories,
    user_id     bigint not null
        constraint fkqwv7rmvc8va8rep7piikrojds
            references users
);

alter table transactions
    owner to ishenaly;